// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bcchduauwyyymvthxgkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjY2hkdWF1d3l5eW12dGh4Z2tmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyMjgxNjcsImV4cCI6MjA4OTgwNDE2N30.NacZyuCbwJUYXOFbAN3dzK2X3UMBMARTzzTR0Cm1hug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);